version: '3.8'

services:
  # Admin Backend
  lccode_admin:
    build:
      context: .
    container_name: lccode_front
    restart: always
    labels:
      traefik.enable: true
      traefik.http.middlewares.traefik-node-app-codefrn-redirect.redirectscheme.scheme: https
      traefik.http.routers.node-app-codefrn.tls.certresolver: letsencrypt_resolver
      traefik.http.routers.node-app-codefrn-http-router.entrypoints: web
      traefik.http.routers.node-app-codefrn-http-router.rule: Host(`${BACKEND_URL}`)
      traefik.http.routers.node-app-codefrn-http-router.middlewares: traefik-node-app-codefrn-redirect
      traefik.http.routers.node-app-codefrn-https-router.entrypoints: websecure
      traefik.http.routers.node-app-codefrn-https-router.tls: 'true'
      traefik.http.routers.node-app-codefrn-https-router.rule: Host(`${BACKEND_URL}`)
      traefik.http.routers.node-app-codefrn-https-router.tls.certresolver: letsencrypt_resolver
      traefik.http.middlewares.redirect-to-https.headers.sslredirect: true
      traefik.http.middlewares.redirect-to-https.headers.sslProxyHeaders.X-Forwarded-Proto: https
      traefik.http.services.node-app-codefrn.loadbalancer.server.port: ${PORT}
      traefik.http.middlewares.force-secure.redirectscheme.scheme: https
      traefik.http.middlewares.force-secure.redirectscheme.permanent: true
    networks:
      - server-setup-2023_lcdev_network
    volumes:
      - ./public/data:/usr/src/app/public/data
      - ./volumes/logs-volume:/usr/src/app/logs

networks:
  server-setup-2023_lcdev_network:
    external: true

